name: Test UI
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: "ui/package-lock.json"
      - run: npm ci --prefix=ui
      - run: cd ui && npx prettier --check ./src
      - run: npm run build --prefix=ui
